#!/bin/bash
# Copyright (c) 2022 Jaehong Kang
# Licensed under Apache License v2.0

while IFS= read -r LINE;
do
    WORKFLOW_COMMANDS="$(echo "$LINE" | sed -E 's/^(\/[^:]+):([0-9]+):([0-9]+): (warning|error): (.*)/::\4 file=\1,line=\2,col=\3::\5/g')"

    case $WORKFLOW_COMMANDS in
    ::*)
        echo "$WORKFLOW_COMMANDS" ;;
    *)
        echo "$LINE" ;;
    esac
done
